id = "qwik"

name = "Qwik"

version = "0.0.1"

schema_version = 1

authors = [
  "Daksh Sharma"
]

description = "Qwik support for Zed"

repository = "https://github.com/frypan05/qwik"

snippets = [
  "./snippets/tsx.json"
]

[language.qwik]
path = "languages/qwik"