name = "Qwik"

grammar = "tsx"

path_suffixes = [
  "tsx",
  "jsx"
]

line_comments = ["// "]

autoclose_before = ";:.,=}])>` \n\t"

brackets = [
  ["{", "}"],
  ["[", "]"],
  ["(", ")"],
  ["<", ">"]
]